development:
  adapter: postgresql
  database: market_place_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: market_place_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: market_place_production
  pool: 5
  timeout: 5000